//
// Created by cse on 12/3/15.
//
#undef START_MAPPING
#undef START_MAPPING_A
#undef START_MAPPING_SUB
#undef START_MAPPING_SUB_A
#undef END_MAPPING
#undef END_MAPPING_SUB

#undef MAPPED_PROP
#undef MAPPED_PROP_ITER
#undef MAPPED_PROP2
#undef MAPPED_PROP3
#undef OBJECT_ID
