//
// Created by cse on 12/3/15.
//
#undef START_MAPPINGHDR
#undef START_MAPPINGHDR_SUB

#undef END_MAPPINGHDR
#undef END_MAPPINGHDR_SUB
#undef END_MAPPING
#undef END_MAPPING_SUB

#undef MAPPED_PROP
#undef MAPPED_PROP2
#undef MAPPED_PROP3
#undef OBJECT_ID
